--- 
- 
  hosts: "192.168.138.128"
  become: false
  name: "Installing 7zip"
  tasks: 
    - 
      name: "Download the 7zip installer"
      win_get_url: 
        dest: "C:\\ansible_examples\\7z2201-x64.exe"
        url: "https://www.7-zip.org/a/7z2201-x64.exe"
    - 
      name: "Install exe"
      win_package: 
        path: "C:\\ansible_examples\\7z2201-x64.exe"
        creates_path: C:\Program Files\7-Zip\7z.exe
        creates_version: 22.01
        state: present
