---
- name: win_reboot module
  hosts: all
  become: false
  gather_facts: true
  tasks:
   - name: reboot host(s)
     win_reboot:
       win_pending_reboot: true
       msg: "Reboot by Ansible"
       pre_reboot_delay: 10
       post_reboot_delay: 10
