---
- name: win_reboot module
  hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: reboot host(s)
      win_reboot:
        when: ansible_date_time [ "time" ] == >19:00pm
        msg: Reboot by Ansible
        pre_reboot_delay: 10
        post_reboot_delay: 10
